### ISSUE TITLE
Framerate issues

### ISSUE THREAD

**Issue by gonutz** [x-hgg-x/arkanoid-go#4]
The framerate is very, very jittery. This makes it hard to even control the panel right. One moment the ball comes flying in fast, then it stops due to a harsh drop in framerate, but I am moving my mouse along with the ball - or so I think - but it "tricks" me and I drop it.

I am on Windows 10 and found the framerate not to be constant at all. The ball does not move smoothly.

**Comment by x-hgg-x** [comment]
I cannot reproduce.
I have tested on an old PC with Windows 10 and it runs smoothly.
You may have problems with your drivers or with OpenGL.

Your problem is probably directly related to [the Ebiten game engine](https://github.com/hajimehoshi/ebiten). Try to run one of the [examples](https://github.com/hajimehoshi/ebiten/tree/master/examples) and post an issue there if you encounter the same problem.

**Comment by gonutz** [comment]
Wow, thanks for fixing the issues so quickly, great job!

I figured this might be a problem of the engine you are using. Still, great job :-)
